name: continuous-integration

on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - name: Install Dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test -- --prod
